### ISSUE TITLE
sleep functions

### ISSUE THREAD

**Issue by camjac251** [feesar/bucket-head#1]
Are the sleep functions necessary in wipe/update.sh? It seems like an awful amount of time that a server would be down for.
Would it be possible to just have it wait until rustserver closes before continuing? Sometimes updates take just 2-5 seconds, and even the it outputs messages at the end like `Updating mods rustserver: Mods update complete`. I was curious if the status code of the process isn't possible, then maybe `grep` with the output possibly could? if the string matches then it knows it completed successfully
This could greatly reduce the amount of time needed for a server to be "down", replacing all `sleep` functions.

**Comment by feesar** [comment]
Thanks for the suggestion, will try to remove the sleep function all over on the next update.

**Comment by feesar** [comment]
Thanks for the suggestion, will try to remove the sleep function all over on the next update.

**Comment by feesar** [comment]
Code refactored for better performance in a new version that is available in the master branch.
