### ISSUE TITLE
Biweekly wipe

### ISSUE THREAD

**Issue by pede** [feesar/bucket-head#2]
Hello Feesar,

First of all thanks alot for sharing this awsome script.
Is there a good way to schedule biweekly wipes or will I need to change the script?

Cronjob fix for biweekly so far:
0 16 8-14 * *    test $(date +\%u) -eq 4 && job.sh 

Do you know a better way? Thank you in advance!

**Comment by feesar** [comment]
Hey @pede,

You can define bi-weekly wipes inside the schedule.cfg file by setting the following

`wipe_minute="0"
wipe_hour="16"
wipe_day="8-14"
wipe_month="*"
wipe_week_day="4"`

`wipe_week_day="4"` is equal to yours `$(date +%u) -eq 4`

Let me know if this works for you.

Cheers.

**Comment by pede** [comment]
Hi @feesar
Thanks for taking your time.
I tried your suggestion but it didn't work :
wipe_minute="0"
wipe_hour="16"
wipe_day="8-14"
wipe_month="*"
wipe_week_day="4"

**Log output:**
[update 18/03/2021 15:55:01] Update disabled or not the time for an update
[update 18/03/2021 16:00:01] Checking for LGSM update
[update 18/03/2021 16:10:01] Update disabled or not the time for an update

This is from crontab guru: https://crontab.guru/#0_16_8-14_*_4
Any ideas why?

**Comment by feesar** [comment]
@pede ,

Your schedule is set to run on 8-14 but you expect it to run on 18
